/* Generated test suite. Every project gets game/tests/game.test.js, runnable with plain Node
   (`node game/tests/game.test.js`) against the project's pinned engine copy. The studio runs it in a
   child process and parses the JSON report. */
'use strict';
const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');

const TEST_SOURCE = String.raw`/* Auto-generated by Local Game Studio. Run: node tests/game.test.js
   Tests: new game, time, economy reconciliation, entities & references, save/load, commissioner
   propagation, every action, long-run stability. Prints a JSON report on the last line. */
'use strict';
const path = require('path');
const fs = require('fs');
const root = path.join(__dirname, '..');
const { loadEngine } = require(path.join(root, 'engine', 'node.js'));
const E = loadEngine();
const gdl = JSON.parse(fs.readFileSync(path.join(root, 'data', 'game.json'), 'utf8'));
for (const f of (fs.existsSync(path.join(root, 'src', 'custom')) ? fs.readdirSync(path.join(root, 'src', 'custom')) : []).filter(f => f.endsWith('.js'))) require(path.join(root, 'src', 'custom', f));
const results = [];
function test(name, area, fn) { const t0 = Date.now(); try { const note = fn(); results.push({ name, area, ok: true, ms: Date.now() - t0, note: note || '' }); } catch (e) { results.push({ name, area, ok: false, ms: Date.now() - t0, error: String(e && e.message || e) }); } }
function assert(c, msg) { if (!c) throw new Error(msg); }
const finiteDeep = (o, where, depth = 0) => { if (depth > 3 || !o || typeof o !== 'object') return; for (const [k, v] of Object.entries(o)) { if (typeof v === 'number') assert(Number.isFinite(v), where + '.' + k + ' = ' + v); else if (v && typeof v === 'object' && !v.__org && !v.__ent && k !== 'hist' && k !== 'ledger') finiteDeep(v, where + '.' + k, depth + 1); } };
function playTicks(g, n, act) {
  const P = g.playerOrg();
  for (let i = 0; i < n; i++) {
    if (act) for (const a of g.listActions(null).slice(0, 4)) { const raw = g.defaultParams(a, P); const pv = g.previewAction(a, P, null, raw); if (pv.ok && (!a.effects.some(o => o.op === 'negotiate'))) g.act(a.id, Object.fromEntries(Object.entries(raw).map(([k, v]) => [k, v && typeof v === 'object' ? v.id : v]))); }
    for (const ev of g.state.events.pending.slice()) g.resolveEvent(ev.iid, 0, true);
    for (const nn of Object.values(g.state.negotiations)) if (nn.org === P.id) g.walkAway(nn.id);
    if (g.state.progression.rescueOpen) g.chooseRescue(0);
    g.tick();
  }
}
let g;
test('New game creates successfully', 'new game', () => { g = E.Game.create(gdl, { seed: 42, headless: true }); assert(g.playerOrg(), 'no player company'); assert(g.diag.errors.length === 0, 'errors at creation: ' + JSON.stringify(g.diag.errors.slice(0, 3))); return Object.keys(g.state.orgs).length + ' companies'; });
test('Default state is valid', 'new game', () => { const P = g.playerOrg(); assert(Number.isFinite(P.cash), 'cash not finite'); assert(g.listActions(null).length > 0, 'no actions available'); finiteDeep(P.m, 'player.m'); return g.listActions(null).length + ' actions available'; });
test('Time advances without NaN or impossible dates', 'time', () => { const d0 = g.cal.dateOf(g.state.tick).getTime(); playTicks(g, 8, false); const d1 = g.cal.dateOf(g.state.tick).getTime(); assert(d1 > d0, 'date did not move'); for (const o of Object.values(g.state.orgs)) { assert(Number.isFinite(o.cash), o.name + ' cash ' + o.cash); finiteDeep(o.m, o.name); } return g.cal.label(g.state.tick); });
test('Cash reconciles with the ledger every tick', 'economy', () => {
  const P = g.playerOrg(); let worst = 0;
  for (let i = 0; i < 12; i++) { const c0 = P.cash; playTicks(g, 1, true); const L = P.ledger.last; let s = 0; for (const [k, v] of Object.entries(L)) if (!(P.ledger.nonCash && P.ledger.nonCash[k])) s += v; worst = Math.max(worst, Math.abs((P.cash - c0) - s)); }
  assert(worst < 1, 'cash moved without a ledger entry (max gap ' + worst + ')'); return 'max gap ' + worst.toFixed(4);
});
test('Revenue and costs are finite', 'economy', () => { const P = g.playerOrg(); assert(Number.isFinite(P.m.revenue) && Number.isFinite(P.m.costs), 'non-finite revenue/costs'); return 'revenue/tick ' + Math.round(P.m.revenue); });
test('Entity ids unique and references valid', 'entities', () => {
  let n = 0;
  for (const k of g.def.kindOrder) { const kd = g.def.kinds[k]; const ids = new Set(); for (const e of g.all(k)) { assert(!ids.has(e.id), 'duplicate id ' + e.id); ids.add(e.id); n++; for (const [f, fd] of Object.entries(kd.fields)) if (fd.type === 'ref' && e[f] != null) assert(g.ent(fd.ref, e[f]), k + '.' + f + ' on ' + e.id + ' points to missing ' + e[f]); if (e.owner != null) assert(g.state.orgs[e.owner], e.id + ' owned by missing company'); } }
  return n + ' entities';
});
test('Deleting an owned entity is handled', 'entities', () => { const P = g.playerOrg(); const k = g.def.kindOrder.find(x => g.owned(x, P.id).length); if (!k) return 'nothing owned'; const e = g.owned(k, P.id)[0]; for (const k2 of g.def.kindOrder) for (const [f, fd] of Object.entries(g.def.kinds[k2].fields)) if (fd.type === 'ref' && fd.ref === k) for (const x of g.refs(k2, f, e.id)) x[f] = null; g.removeEntity(e); playTicks(g, 2, false); assert(!g.diag.errors.length, JSON.stringify(g.diag.errors.slice(0, 2))); return 'removed ' + e.id; });
test('Save → load preserves state', 'save', () => { const s1 = g.serialize(); const g2 = E.Game.load(gdl, s1, { headless: true }); assert(g2.state.tick === g.state.tick, 'tick changed'); assert(Math.abs(g2.playerOrg().cash - g.playerOrg().cash) < 1e-6, 'cash changed'); assert(Object.keys(g2.state.ents).length === Object.keys(g.state.ents).length, 'kinds changed'); g2.tick(); assert(!g2.diag.errors.length, 'tick after load failed'); return (s1.length / 1024).toFixed(0) + ' KB'; });
test('Old saves migrate (missing fields filled)', 'save', () => { const st = JSON.parse(g.serialize()); delete st.history; delete st.settings; for (const o of Object.values(st.orgs)) delete o.res; const g3 = E.Game.load(gdl, st, { headless: true }); g3.tick(); assert(g3.state.history && g3.playerOrg().res, 'migration failed'); });
test('Commissioner edits propagate to the simulation', 'commissioner', () => {
  const P = g.playerOrg(); const before = P.cash; g.addCash(P, 1e6, 'Commissioner'); assert(Math.abs(P.cash - before - 1e6) < 1, 'cash edit not applied');
  const op = g.def.kindOrder.find(k => g.def.kinds[k].operate && g.owned(k, P.id).length);
  if (op) { const keys = Object.keys(g.params).filter(k => /demand|size|market/i.test(k)); playTicks(g, 1, false); const sold0 = g.owned(op, P.id).reduce((a, e) => a + (e._demand || 0), 0); if (keys.length) { const k = keys[0]; const old = g.params[k]; g.params[k] = old * 0.3; playTicks(g, 1, false); const sold1 = g.owned(op, P.id).reduce((a, e) => a + (e._demand || 0), 0); g.params[k] = old; assert(sold1 < sold0, 'changing ' + k + ' did not change demand (' + sold0 + ' → ' + sold1 + ')'); } }
  const ph = (g.def.world.cycle && g.def.world.cycle.phases) || []; if (ph.length > 1) { const target = ph.find(p => p.id !== g.state.world.phase).id; g.forcePhase(target); playTicks(g, 1, false); assert(g.state.world.phase === target, 'forced phase did not apply'); }
  return 'cash, params and phase edits flowed through';
});
test('Every global action previews and executes cleanly', 'actions', () => {
  const P = g.playerOrg(); let ran = 0; const errs0 = g.diag.errors.length;
  for (const a of g.listActions(null)) { const raw = g.defaultParams(a, P); const pv = g.previewAction(a, P, null, raw); if (pv.ok && !a.effects.some(o => o.op === 'negotiate')) { const r = g.act(a.id, Object.fromEntries(Object.entries(raw).map(([k, v]) => [k, v && typeof v === 'object' ? v.id : v]))); if (r.ok) ran++; } }
  for (const k of g.def.kindOrder) for (const e of g.owned(k, P.id).slice(0, 2)) for (const a of g.listActions(e)) { if (a.danger) continue; const raw = g.defaultParams(a, P, e); const pv = g.previewAction(a, P, e, raw); if (pv.ok) { const r = g.act(a.id, Object.fromEntries(Object.entries(raw).map(([kk, v]) => [kk, v && typeof v === 'object' ? v.id : v])), { self: e }); if (r.ok) ran++; } }
  assert(g.diag.errors.length === errs0, 'errors: ' + JSON.stringify(g.diag.errors.slice(errs0, errs0 + 3)));
  return ran + ' actions executed';
});
test('Negotiations open, respond and close', 'actions', () => {
  const P = g.playerOrg(); const nd = (gdl.negotiations || [])[0]; if (!nd) return 'no negotiations in this game';
  const them = nd.with === 'org' ? g.liveOrgs().find(o => !o.isPlayer && o.level < 3) : g.all(nd.with)[0];
  if (!them) return 'no counterparty available';
  const n = g.startNegotiation(nd.id, them, P, g.scope()); assert(n, 'could not start'); const r = g.offer(n.id, n.terms); assert(r.ok, 'offer failed'); if (g.state.negotiations[n.id]) g.walkAway(n.id); return 'response: ' + r.status;
});
test('Long run: 10 years stays stable', 'long run', () => {
  const g4 = E.Game.create(gdl, { seed: 7, headless: true, options: { noBankruptcy: true } }); const t0 = Date.now();
  playTicks(g4, g4.cal.perYear * 10, true);
  assert(!g4.diag.errors.length, JSON.stringify(g4.diag.errors.slice(0, 3)));
  for (const o of Object.values(g4.state.orgs)) assert(Number.isFinite(o.cash) && Math.abs(o.cash) < 1e15, o.name + ' cash exploded: ' + o.cash);
  const ents = g4.def.kindOrder.reduce((a, k) => a + g4.all(k).length, 0); const size = g4.serialize().length;
  assert(size < 25e6, 'save too large: ' + size);
  return ((Date.now() - t0) / (g4.cal.perYear * 10)).toFixed(1) + ' ms/tick · ' + ents + ' entities · save ' + (size / 1e6).toFixed(1) + ' MB';
});
const passed = results.filter(r => r.ok).length;
for (const r of results) console.log((r.ok ? 'PASS ' : 'FAIL ') + r.area.padEnd(13) + r.name + (r.ok ? (r.note ? '  (' + r.note + ')' : '') : '  — ' + r.error));
console.log(JSON.stringify({ passed, failed: results.length - passed, results }));
process.exitCode = passed === results.length ? 0 : 1;
`;

function writeSuite(gameDir) {
  fs.mkdirSync(path.join(gameDir, 'tests'), { recursive: true });
  const p = path.join(gameDir, 'tests', 'game.test.js');
  fs.writeFileSync(p, TEST_SOURCE);
  return p;
}
function runSuite(gameDir, timeoutMs = 15 * 60 * 1000) {
  const p = writeSuite(gameDir);
  return new Promise((resolve) => {
    execFile(process.execPath, [p], { cwd: gameDir, timeout: timeoutMs, maxBuffer: 20 * 1024 * 1024 }, (err, stdout, stderr) => {
      const lines = String(stdout).trim().split('\n');
      let report = null;
      try { report = JSON.parse(lines[lines.length - 1]); } catch (e) { report = { passed: 0, failed: 1, results: [{ name: 'Test runner', area: 'runner', ok: false, error: String(stderr || (err && err.message) || 'no output').slice(0, 2000) }] }; }
      report.log = lines.slice(0, -1).join('\n');
      resolve(report);
    });
  });
}
module.exports = { writeSuite, runSuite, TEST_SOURCE };
